# Generated by Django 4.2.10 on 2024-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_check_printed',
            field=models.BooleanField(default=False),
        ),
    ]
