# Generated by Django 4.2.11 on 2024-05-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sifariş', 'verbose_name_plural': 'Sifarişlər'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Sifariş məhsulu', 'verbose_name_plural': 'Sifariş məhsulları'},
        ),
    ]
