# Generated by Django 4.2.11 on 2024-05-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='waitress_id',
            field=models.CharField(blank=True, help_text='Ofisiant kodu və adı.', max_length=90, null=True),
        ),
    ]
