# Generated by Django 4.2.11 on 2024-05-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_statistics_waitress_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='waitress_id',
            new_name='waitress_info',
        ),
    ]
