# Generated by Django 4.2.11 on 2024-05-13 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_meal_created_at_alter_mealcategory_created_at'),
        ('tables', '0007_alter_room_created_at_alter_table_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_rename_waitress_id_statistics_waitress_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='tarix'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_check_printed',
            field=models.BooleanField(default=False, verbose_name='Çek çıxarılıb'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Ödənilib'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meals',
            field=models.ManyToManyField(through='orders.OrderItem', to='meals.meal', verbose_name='Yemək'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tables.table', verbose_name='Stol'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ümumi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='waitress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Ofisiant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='tarix'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='tarix'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='title',
            field=models.CharField(choices=[('daily', 'Günlük'), ('monthly', 'Aylıq'), ('yearly', 'İllik'), ('per_waitress', 'Ofisianta görə')], default='daily', max_length=32, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ümumi'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='waitress_info',
            field=models.CharField(blank=True, help_text='Ofisiant kodu və adı.', max_length=90, null=True, verbose_name='Ofisiant'),
        ),
    ]
