# Generated by Django 4.2.11 on 2024-05-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_created_at_alter_order_is_check_printed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tarix'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tarix'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tarix'),
        ),
    ]
