# Generated by Django 4.2.11 on 2024-05-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_created_at_alter_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='tarix'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='tarix'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='tarix'),
        ),
    ]
