# Generated by Django 4.2.11 on 2024-05-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_statistics_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='title',
            field=models.CharField(choices=[('till_now', 'Bu günə kimi'), ('daily', 'Günlük'), ('monthly', 'Aylıq'), ('yearly', 'İllik'), ('per_waitress', 'Ofisianta görə')], default='till_now', max_length=32, verbose_name='Başlıq'),
        ),
    ]
