# Generated by Django 4.2.11 on 2024-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_statistics_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='is_z_checked',
            field=models.BooleanField(default=False),
        ),
    ]
