# Generated by Django 4.2.11 on 2024-05-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_statistics_is_z_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='statistics', to='orders.order'),
        ),
    ]
