# Generated by Django 4.2.11 on 2024-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_statistics_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='statistics', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='title',
            field=models.CharField(choices=[('till_now', 'Bu günə kimi'), ('daily', 'Günlük'), ('monthly', 'Aylıq'), ('yearly', 'İllik'), ('per_waitress', 'Ofisianta görə')], default='daily', max_length=32, verbose_name='Başlıq'),
        ),
    ]
