# Generated by Django 4.2.11 on 2024-05-31 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_meal_created_at_alter_mealcategory_created_at'),
        ('orders', '0021_historicalorderitem_historicalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderitem',
            name='is_deleted_by_adminstrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_deleted_by_adminstrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalorderitem',
            name='meal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meals.meal', verbose_name='Yemək'),
        ),
        migrations.AlterField(
            model_name='historicalorderitem',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.order', verbose_name='Sifariş'),
        ),
        migrations.AlterField(
            model_name='historicalorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Məbləğ'),
        ),
        migrations.AlterField(
            model_name='historicalorderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Miqdar'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal', verbose_name='Yemək'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Sifariş'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Məbləğ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Miqdar'),
        ),
    ]
