# Generated by Django 4.2.11 on 2024-06-02 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_historicalorderitem_is_deleted_by_adminstrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderitem',
            name='item_added_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_added_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
