# Generated by Django 4.2.15 on 2024-10-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_historicalorderitem_item_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
