# Generated by Django 4.2.15 on 2024-10-03 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0024_historicalorder_is_deleted_order_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStatistics',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='tarix')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(choices=[('till_now', 'Bu günə kimi'), ('daily', 'Günlük'), ('monthly', 'Aylıq'), ('yearly', 'İllik'), ('per_waitress', 'Ofisianta görə')], default='daily', max_length=32, verbose_name='Başlıq')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ümumi')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarix')),
                ('waitress_info', models.CharField(blank=True, help_text='Ofisiant kodu və adı.', max_length=90, null=True, verbose_name='Ofisiant')),
                ('is_z_checked', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Statistika',
                'verbose_name_plural': 'historical Statistikalar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
