# Generated by Django 4.2.15 on 2024-10-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_historicalstatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sifariş', 'verbose_name_plural': 'historical Sifarişlər 🍽️'},
        ),
        migrations.AlterModelOptions(
            name='historicalorderitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sifariş məhsulu', 'verbose_name_plural': 'historical Sifariş məhsulları 🥘'},
        ),
        migrations.AlterModelOptions(
            name='historicalstatistics',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Statistika', 'verbose_name_plural': 'historical Statistikalar 📊'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sifariş', 'verbose_name_plural': 'Sifarişlər 🍽️'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Sifariş məhsulu', 'verbose_name_plural': 'Sifariş məhsulları 🥘'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Statistika', 'verbose_name_plural': 'Statistikalar 📊'},
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
