# Generated by Django 4.2.15 on 2024-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_historicalorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorderitem',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_main',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
