# Generated by Django 4.2.15 on 2025-04-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_remove_historicalorderitem_is_main_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstatistics",
            name="title",
            field=models.CharField(
                choices=[
                    ("till_now", "Hesabat"),
                    ("daily", "Günlük"),
                    ("monthly", "Aylıq"),
                    ("yearly", "İllik"),
                    ("per_waitress", "Ofisianta görə"),
                ],
                default="daily",
                max_length=32,
                verbose_name="Başlıq",
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="title",
            field=models.CharField(
                choices=[
                    ("till_now", "Hesabat"),
                    ("daily", "Günlük"),
                    ("monthly", "Aylıq"),
                    ("yearly", "İllik"),
                    ("per_waitress", "Ofisianta görə"),
                ],
                default="daily",
                max_length=32,
                verbose_name="Başlıq",
            ),
        ),
    ]
