# Generated by Django 4.2.15 on 2025-04-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_alter_historicalstatistics_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstatistics",
            name="is_z_checked",
            field=models.BooleanField(
                default=False, verbose_name="Hesabat təsdiqlənib?"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="is_z_checked",
            field=models.BooleanField(
                default=False, verbose_name="Hesabat təsdiqlənib?"
            ),
        ),
    ]
