# Generated by Django 4.2.15 on 2025-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_alter_historicalstatistics_is_z_checked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="customer_count",
            field=models.PositiveIntegerField(default=1, verbose_name="Müştəri sayı"),
        ),
        migrations.AddField(
            model_name="historicalorderitem",
            name="customer_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Müştəri №"),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_count",
            field=models.PositiveIntegerField(default=1, verbose_name="Müştəri sayı"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="customer_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Müştəri №"),
        ),
    ]
