# Generated by Django 4.2.15 on 2025-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_historicalorder_customer_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorderitem",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
