# Generated by Django 5.2 on 2025-04-22 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0031_historicalorderitem_confirmed_orderitem_confirmed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstatistics",
            name="card_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total card"
            ),
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="cash_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total cash"
            ),
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Shift end time"
            ),
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ended by",
            ),
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="initial_cash",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Initial cash"
            ),
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="Is closed"),
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="other_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total other"
            ),
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="remaining_cash",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Remaining cash",
            ),
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Shift start time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Started by",
            ),
        ),
        migrations.AddField(
            model_name="historicalstatistics",
            name="withdrawn_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Withdrawn amount",
            ),
        ),
        migrations.AddField(
            model_name="statistics",
            name="card_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total card"
            ),
        ),
        migrations.AddField(
            model_name="statistics",
            name="cash_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total cash"
            ),
        ),
        migrations.AddField(
            model_name="statistics",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Shift end time"
            ),
        ),
        migrations.AddField(
            model_name="statistics",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts_ended",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ended by",
            ),
        ),
        migrations.AddField(
            model_name="statistics",
            name="initial_cash",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Initial cash"
            ),
        ),
        migrations.AddField(
            model_name="statistics",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="Is closed"),
        ),
        migrations.AddField(
            model_name="statistics",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="statistics",
            name="other_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total other"
            ),
        ),
        migrations.AddField(
            model_name="statistics",
            name="remaining_cash",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Remaining cash",
            ),
        ),
        migrations.AddField(
            model_name="statistics",
            name="start_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Shift start time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statistics",
            name="started_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts_started",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Started by",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statistics",
            name="withdrawn_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Withdrawn amount",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="waitress_info",
            field=models.CharField(
                blank=True, max_length=90, null=True, verbose_name="Ofisiant"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="waitress_info",
            field=models.CharField(
                blank=True, max_length=90, null=True, verbose_name="Ofisiant"
            ),
        ),
    ]
