# Generated by Django 5.2 on 2025-04-22 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0032_historicalstatistics_card_total_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstatistics",
            name="card_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Kartla ümumi"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="cash_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Nağd qazanılmış",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Növbənin bitmə vaxtı"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Növbəni bağlayan",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="initial_cash",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Başlanğıc nağd",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="Növbə bağlandı?"),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="is_z_checked",
            field=models.BooleanField(
                default=False, verbose_name="Hesabat təsdiqləndi?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Qeydlər"),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="other_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Digər ödənişlər",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="remaining_cash",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Qalan nağd"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="start_time",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Növbənin başlanma vaxtı"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Növbəni açan",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Ümumi məbləğ"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="withdrawn_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Çıxarılan məbləğ",
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="card_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Kartla ümumi"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="cash_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Nağd qazanılmış",
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Növbənin bitmə vaxtı"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts_ended",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Növbəni bağlayan",
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="initial_cash",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Başlanğıc nağd",
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="Növbə bağlandı?"),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="is_z_checked",
            field=models.BooleanField(
                default=False, verbose_name="Hesabat təsdiqləndi?"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Qeydlər"),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="orders",
            field=models.ManyToManyField(
                blank=True,
                related_name="statistics",
                to="orders.order",
                verbose_name="Sifarişlər",
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="other_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Digər ödənişlər",
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="remaining_cash",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Qalan nağd"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="start_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Növbənin başlanma vaxtı"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="started_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts_started",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Növbəni açan",
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Ümumi məbləğ"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="withdrawn_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Çıxarılan məbləğ",
            ),
        ),
    ]
