# Generated by Django 5.2 on 2025-04-23 13:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_alter_historicalstatistics_card_total_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItemDeletionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField(verbose_name="Sifariş ID")),
                (
                    "order_item_id",
                    models.IntegerField(verbose_name="Sifariş Məhsulu ID"),
                ),
                ("table_id", models.IntegerField(verbose_name="Stol ID")),
                (
                    "waitress_name",
                    models.CharField(max_length=150, verbose_name="Ofisiantın Adı"),
                ),
                (
                    "meal_name",
                    models.CharField(max_length=255, verbose_name="Yeməyin Adı"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Miqdar"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Qiymət"
                    ),
                ),
                (
                    "customer_number",
                    models.PositiveIntegerField(verbose_name="Müştəri №"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("return", "Anbara qaytarma"), ("waste", "Tullantı")],
                        max_length=20,
                        verbose_name="Səbəb",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Silinmə Vaxtı"
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_orderitem_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Silən İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Silinmiş Sifariş Məhsulu",
                "verbose_name_plural": "Silinmiş Sifariş Məhsulları",
                "indexes": [
                    models.Index(
                        fields=["reason", "deleted_at"],
                        name="orders_orde_reason_7c8b27_idx",
                    )
                ],
            },
        ),
    ]
