# Generated by Django 5.2 on 2025-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_alter_historicalstatistics_card_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorderitem",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Şərh"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Şərh"),
        ),
    ]
