# Generated by Django 5.2 on 2025-04-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0034_historicalorderitem_comment_orderitem_comment"),
        ("orders", "0035_orderitemdeletionlog_comment"),
    ]

    operations = []
