# Generated by Django 5.2 on 2025-04-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0037_historicalorderitem_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorderitem",
            name="transfer_comment",
            field=models.TextField(blank=True, null=True, verbose_name="Şərh"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="transfer_comment",
            field=models.TextField(blank=True, null=True, verbose_name="Şərh"),
        ),
    ]
