# Generated by Django 5.2 on 2025-04-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0038_historicalorderitem_transfer_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, verbose_name="Məbləğ"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, verbose_name="Məbləğ"
            ),
        ),
    ]
