# Generated by Django 5.2 on 2025-04-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_merge_20250424_2345'),
        ('orders', '0039_alter_historicalorderitem_price_and_more'),
    ]

    operations = [
    ]
