# Generated by Django 5.2 on 2025-04-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_merge_20250425_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderitem',
            name='transfer_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Transfer Şərh'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='transfer_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Transfer Şərh'),
        ),
    ]
