# Generated by Django 5.2 on 2025-05-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0040_merge_20250425_1150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="is_check_printed",
            field=models.BooleanField(
                default=False, verbose_name="Müştəri üçün çek çıxarılıb ?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silinmiş ?"),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="is_main",
            field=models.BooleanField(
                default=False, verbose_name="Masanın əsas sifarişi ?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Ödənilib ?"),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Ümumi məbləğ"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Hazırlanmaya göndərildi ?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="is_deleted_by_adminstrator",
            field=models.BooleanField(
                default=False, verbose_name="Adminstrator tərəfindən silinib ?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="transfer_comment",
            field=models.TextField(blank=True, null=True, verbose_name="Transfer Şərh"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_check_printed",
            field=models.BooleanField(
                default=False, verbose_name="Müştəri üçün çek çıxarılıb ?"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silinmiş ?"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_main",
            field=models.BooleanField(
                default=False, verbose_name="Masanın əsas sifarişi ?"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Ödənilib ?"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Ümumi məbləğ"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Hazırlanmaya göndərildi ?"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="is_deleted_by_adminstrator",
            field=models.BooleanField(
                default=False, verbose_name="Adminstrator tərəfindən silinib ?"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="transfer_comment",
            field=models.TextField(blank=True, null=True, verbose_name="Transfer Şərh"),
        ),
    ]
