# Generated by Django 5.2 on 2025-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0041_alter_historicalorder_is_check_printed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Yeniləndi"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Yeniləndi"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Yeniləndi"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Yeniləndi"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Yeniləndi"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Yeniləndi"
            ),
        ),
    ]
