# Generated by Django 5.2 on 2025-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0042_alter_historicalorder_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstatistics",
            name="withdrawn_notes",
            field=models.TextField(blank=True, verbose_name="Qeydlər"),
        ),
        migrations.AddField(
            model_name="statistics",
            name="withdrawn_notes",
            field=models.TextField(blank=True, verbose_name="Qeydlər"),
        ),
    ]
