# Generated by Django 5.2 on 2025-05-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0043_historicalstatistics_withdrawn_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstatistics",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Başlanma Qeydi"),
        ),
        migrations.AlterField(
            model_name="historicalstatistics",
            name="withdrawn_notes",
            field=models.TextField(blank=True, verbose_name="Bağlanma Qeydi"),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Başlanma Qeydi"),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="withdrawn_notes",
            field=models.TextField(blank=True, verbose_name="Bağlanma Qeydi"),
        ),
    ]
