# Generated by Django 5.2 on 2025-05-19 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0044_alter_historicalstatistics_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="tarix"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Yeniləndi"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlanğıc tarixi")),
                ("end_date", models.DateField(verbose_name="Bitiş tarixi")),
                (
                    "cash_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Nağd məbləğ",
                    ),
                ),
                (
                    "card_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Kart məbləği",
                    ),
                ),
                (
                    "other_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Digər ödənişlər",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ümumi məbləğ",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="summaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hesabatı yaradan",
                    ),
                ),
                (
                    "statistics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="summaries",
                        to="orders.statistics",
                        verbose_name="Statistikalar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarix aralığı hesabatı",
                "verbose_name_plural": "Tarix aralığı hesabatları 📊",
                "ordering": ["-created_at"],
            },
        ),
    ]
