# Generated by Django 5.2 on 2025-05-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0045_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="summary",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ümumi hesabat",
                "verbose_name_plural": "Ümumi hesabatlar 📊",
            },
        ),
    ]
