# Generated by Django 5.2 on 2025-09-19 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0046_alter_summary_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkPeriodConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad")),
                ("start_time", models.TimeField(verbose_name="Başlama vaxtı")),
                ("end_time", models.TimeField(verbose_name="Bitmə vaxtı")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "İş Dövrü Konfiqurasiyası",
                "verbose_name_plural": "İş Dövrü Konfiqurasiyaları",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstatistics",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Statistika",
                "verbose_name_plural": "historical Hesabatlar 📊",
            },
        ),
        migrations.AlterModelOptions(
            name="statistics",
            options={
                "verbose_name": "Statistika",
                "verbose_name_plural": "Hesabatlar 📊",
            },
        ),
        migrations.AlterField(
            model_name="summary",
            name="statistics",
            field=models.ManyToManyField(
                blank=True,
                related_name="summaries",
                to="orders.statistics",
                verbose_name="Hesabatlar",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="tarix"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Yeniləndi"
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Başlama tarixi və vaxtı"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(verbose_name="Bitmə tarixi və vaxtı"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ümumi məbləğ",
                    ),
                ),
                (
                    "cash_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Nağd ümumi",
                    ),
                ),
                (
                    "card_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Kartla ümumi",
                    ),
                ),
                (
                    "other_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Digər ödənişlər",
                    ),
                ),
                (
                    "unpaid_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ödənilməmiş ümumi",
                    ),
                ),
                (
                    "orders",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reports",
                        to="orders.order",
                        verbose_name="Sifarişlər",
                    ),
                ),
                (
                    "work_period_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.workperiodconfig",
                        verbose_name="İş Dövrü Konfiqurasiyası",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reportlar",
                "unique_together": {
                    ("work_period_config", "start_datetime", "end_datetime")
                },
            },
        ),
    ]
