# Generated by Django 4.2.28 on 2026-03-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_workperiodconfig_alter_historicalstatistics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawnList',
            fields=[
            ],
            options={
                'verbose_name': 'Çıxarılmış Məbləğ',
                'verbose_name_plural': 'Çıxarılmış Məbləğlər 💰',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.statistics',),
        ),
        migrations.AddField(
            model_name='historicalstatistics',
            name='withdrawn_from_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kartdan çıxarılan məbləğ'),
        ),
        migrations.AddField(
            model_name='historicalstatistics',
            name='withdrawn_from_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Digər ödənişlərdən çıxarılan məbləğ'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='withdrawn_from_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kartdan çıxarılan məbləğ'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='withdrawn_from_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Digər ödənişlərdən çıxarılan məbləğ'),
        ),
    ]
