# Generated by Django 5.2.7 on 2026-01-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_workperiodconfig_alter_historicalstatistics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawnList',
            fields=[
            ],
            options={
                'verbose_name': 'Çıxarılmış Məbləğ',
                'verbose_name_plural': 'Çıxarılmış Məbləğlər 💰',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.statistics',),
        ),
    ]
