# Generated by Django 4.2.28 on 2026-03-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_withdrawnlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatistics',
            name='remaining_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qalan kart'),
        ),
        migrations.AddField(
            model_name='historicalstatistics',
            name='remaining_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qalan Digər ödənişlər'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='remaining_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qalan kart'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='remaining_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qalan Digər ödənişlər'),
        ),
    ]
