# Generated by Django 5.2.7 on 2026-03-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_withdrawnlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatistics',
            name='initial_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Başlanğıc kart'),
        ),
        migrations.AddField(
            model_name='historicalstatistics',
            name='initial_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Başlanğıc Digər ödənişlər'),
        ),
        migrations.AddField(
            model_name='historicalstatistics',
            name='remaining_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qalan kart'),
        ),
        migrations.AddField(
            model_name='historicalstatistics',
            name='remaining_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qalan Digər ödənişlər'),
        ),
        migrations.AddField(
            model_name='historicalstatistics',
            name='withdrawn_from_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kartdan çıxarılan məbləğ'),
        ),
        migrations.AddField(
            model_name='historicalstatistics',
            name='withdrawn_from_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Digər ödənişlərdən çıxarılan məbləğ'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='initial_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Başlanğıc kart'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='initial_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Başlanğıc Digər ödənişlər'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='remaining_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qalan kart'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='remaining_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qalan Digər ödənişlər'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='withdrawn_from_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kartdan çıxarılan məbləğ'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='withdrawn_from_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Digər ödənişlərdən çıxarılan məbləğ'),
        ),
    ]
