# Generated by Django 4.2.28 on 2026-03-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_historicalstatistics_remaining_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatistics',
            name='initial_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Başlanğıc kart'),
        ),
        migrations.AddField(
            model_name='historicalstatistics',
            name='initial_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Başlanğıc Digər ödənişlər'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='initial_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Başlanğıc kart'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='initial_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Başlanğıc Digər ödənişlər'),
        ),
    ]
