# Generated by Django 4.2.11 on 2024-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_options_alter_mealcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
