# Generated by Django 4.2.11 on 2024-05-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_meal_created_at_alter_mealcategory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tarix'),
        ),
        migrations.AlterField(
            model_name='mealcategory',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tarix'),
        ),
    ]
