# Generated by Django 4.2.15 on 2025-04-12 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0007_alter_meal_created_at_alter_mealcategory_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="tarix"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Yemək kateqoriyası qrupu",
                "verbose_name_plural": "Yemək kateqoriya qrupları",
            },
        ),
        migrations.AddField(
            model_name="mealcategory",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="meals.mealgroup",
            ),
        ),
    ]
