# Generated by Django 4.2.15 on 2025-04-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("printers", "0002_preparationplace"),
        ("meals", "0008_mealgroup_mealcategory_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="preparation_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="printers.preparationplace",
            ),
        ),
    ]
