# Generated by Django 5.2 on 2025-04-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0009_meal_preparation_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealcategory",
            name="is_extra",
            field=models.BooleanField(
                default=False, help_text="price will be sent from api"
            ),
        ),
    ]
