# Generated by Django 5.2 on 2025-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0010_mealcategory_is_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Yeniləndi"
            ),
        ),
        migrations.AlterField(
            model_name="mealcategory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Yeniləndi"
            ),
        ),
        migrations.AlterField(
            model_name="mealgroup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Yeniləndi"
            ),
        ),
    ]
