# Generated by Django 4.2.27 on 2026-02-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_alter_receipt_type'),
        ('meals', '0011_alter_meal_updated_at_alter_mealcategory_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealgroup',
            options={'verbose_name': 'Yemək kateqoriyası qrupu', 'verbose_name_plural': 'Yemək kateqoriyaları qrupları'},
        ),
        migrations.AddField(
            model_name='meal',
            name='preparation_places',
            field=models.ManyToManyField(blank=True, help_text='Bu yemək üçün çap olunacaq hazırlanma yerləri', related_name='meals_multi', to='printers.preparationplace', verbose_name='Hazırlanma Yerləri'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='preparation_place',
            field=models.ForeignKey(blank=True, help_text='Deprecated: Use preparation_places instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals_single', to='printers.preparationplace'),
        ),
    ]
