# Generated by Django 5.2.7 on 2026-02-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_alter_mealgroup_options_meal_preparation_places_and_more'),
    ]

    operations = [
    ]
