# Generated by Django 4.2.27 on 2026-02-10 13:57

from django.db import migrations


def migrate_preparation_places(apps, schema_editor):
    """
    Migrate existing single preparation_place to the new preparation_places M2M field
    """
    Meal = apps.get_model('meals', 'Meal')
    
    for meal in Meal.objects.all():
        # If the meal has a single preparation_place, add it to preparation_places
        if meal.preparation_place:
            meal.preparation_places.add(meal.preparation_place)


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: copy first preparation_place from M2M back to FK
    """
    Meal = apps.get_model('meals', 'Meal')
    
    for meal in Meal.objects.all():
        # Get the first preparation place from M2M if exists
        first_place = meal.preparation_places.first()
        if first_place:
            meal.preparation_place = first_place
            meal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_alter_mealgroup_options_meal_preparation_places_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_preparation_places, reverse_migration),
    ]
