# Generated by Django 5.2 on 2025-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Nağd"), ("card", "Kart"), ("other", "Digər")],
                max_length=20,
                null=True,
                verbose_name="Ödəniş növü",
            ),
        ),
    ]
