# Generated by Django 4.2.27 on 2025-12-10 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_alter_payment_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlanğıc tarixi')),
                ('end_date', models.DateField(verbose_name='Son tarixi')),
                ('start_time', models.TimeField(verbose_name='Başlanğıc saatı')),
                ('end_time', models.TimeField(verbose_name='Son saatı')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ümumi məbləğ')),
                ('payment_count', models.PositiveIntegerField(default=0, verbose_name='Ödəniş sayı')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nağd məbləğ')),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kart məbləğ')),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Digər məbləğ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdı')),
            ],
            options={
                'verbose_name': 'Ödəniş hesablaması',
                'verbose_name_plural': 'Ödəniş hesablamaları',
                'ordering': ['-created_at'],
            },
        ),
    ]
