# Generated by Django 5.2.7 on 2025-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentcalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcalculation',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='payment_calculations', to='payments.payment', verbose_name='Ödənişlər'),
        ),
    ]
