# Generated by Django 5.2.7 on 2026-01-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentcalculation_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcalculation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sifarişlərin cəmi'),
        ),
    ]
