# Generated by Django 4.2.11 on 2024-05-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_room_created_at_room_updated_at_table_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Otaq', 'verbose_name_plural': 'Otaqlar'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Stol', 'verbose_name_plural': 'Stollar'},
        ),
    ]
