# Generated by Django 4.2.11 on 2024-05-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_room_options_alter_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Zal', 'verbose_name_plural': 'Zallar'},
        ),
    ]
