# Generated by Django 4.2.11 on 2024-05-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='tarix'),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='tarix'),
        ),
    ]
