# Generated by Django 5.2 on 2025-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0009_alter_room_created_at_alter_table_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Yeniləndi"
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Yeniləndi"
            ),
        ),
    ]
