# Generated by Django 4.2.11 on 2024-05-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('waitress', 'Ofisiant'), ('captain_waitress', 'Kapitan Ofisiant'), ('admin', 'Administrator'), ('restaurant', 'Restaurant Sahibi')], max_length=32, null=True),
        ),
    ]
