# Generated by Django 4.2.15 on 2024-10-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Ofisiant və Menecer', 'verbose_name_plural': 'Ofisiant və Menecerlər'},
        ),
    ]
