# Generated by Django 5.2 on 2025-04-15 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftHandover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_start",
                    models.DateTimeField(verbose_name="Növbənin Başlanğıcı"),
                ),
                ("shift_end", models.DateTimeField(verbose_name="Növbənin Sonu")),
                (
                    "cash_in_kassa",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Kassadakı Məbləğ"
                    ),
                ),
                (
                    "expected_cash",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Gözlənilən Məbləğ",
                    ),
                ),
                (
                    "discrepancy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Uyğunluq Fərqi",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Təsdiqləndi?"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiqlənmə Vaxtı"
                    ),
                ),
                (
                    "is_overridden",
                    models.BooleanField(
                        default=False, verbose_name="İdarə Tərəfindən Dəyişdirildi?"
                    ),
                ),
                (
                    "overridden_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dəyişdirilmə Vaxtı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_handover_from",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Çıxan Əməkdaş",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_handover_to",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gələn Əməkdaş",
                    ),
                ),
            ],
            options={
                "verbose_name": "Növbə Təslimi",
                "verbose_name_plural": "Növbə Təslimləri",
                "ordering": ["-created_at"],
            },
        ),
    ]
