# Generated by Django 5.2 on 2025-04-16 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_shifthandover_is_overridden_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shifthandover",
            name="from_notes",
            field=models.TextField(blank=True, verbose_name="Təhvil verənin qeydləri"),
        ),
        migrations.AlterField(
            model_name="shifthandover",
            name="from_user",
            field=models.ForeignKey(
                limit_choices_to={"type": "admin"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_handover_from",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Təhvil verən",
            ),
        ),
        migrations.AlterField(
            model_name="shifthandover",
            name="to_notes",
            field=models.TextField(blank=True, verbose_name="Təhvil alanın qeydləri"),
        ),
        migrations.AlterField(
            model_name="shifthandover",
            name="to_user",
            field=models.ForeignKey(
                limit_choices_to={"type": "admin"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_handover_to",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Təhvil alan",
            ),
        ),
    ]
