# Generated by Django 5.2 on 2025-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_shifthandover_from_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Yeniləndi"
            ),
        ),
    ]
