# Generated by Django 4.2.28 on 2026-04-03 18:35

import apps.users.models.token
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.users.models.token.generate_token, max_length=64, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('expires_at', models.DateTimeField(default=apps.users.models.token.default_expiry, verbose_name='Bitmə tarixi')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Son istifadə tarixi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_tokens', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Admin Auth Token',
                'verbose_name_plural': 'Admin Auth Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
