# Generated by Django 4.2.28 on 2026-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Format: 994XXXXXXXXX (ölkə kodu ilə birlikdə)', max_length=20, unique=True, verbose_name='Telefon nömrəsi')),
                ('name', models.CharField(blank=True, help_text="Nömrə sahibinin adı və ya qeydi (məsələn: 'Rəsmi sahibi', 'Müdir')", max_length=100, verbose_name='Ad/Qeyd')),
                ('is_active', models.BooleanField(default=True, help_text='Deaktiv nömrələrə bildiriş göndərilməyəcək', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə edilmə tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'WhatsApp Konfiqurasiyası',
                'verbose_name_plural': 'WhatsApp Konfiqurasiyaları',
                'ordering': ['-is_active', 'created_at'],
            },
        ),
    ]
