# Generated by Django 4.2.28 on 2026-10-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_fix_inventory_restaurant_columns'),
        ('users', '0015_restaurant_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Qoşulmuş nömrə')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='Qoşulma vaxtı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yeniləndi')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.restaurant', verbose_name='Restoran')),
            ],
            options={
                'verbose_name': 'WhatsApp sessiyası',
                'verbose_name_plural': 'WhatsApp sessiyaları',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Alıcı nömrə')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='Alıcı')),
                ('from_number', models.CharField(blank=True, max_length=20, verbose_name='Göndərən nömrə')),
                ('body', models.TextField(blank=True, verbose_name='Mesaj')),
                ('kind', models.CharField(choices=[('order_deletion', 'Sifariş silinməsi'), ('text', 'Mesaj'), ('intake_reply', 'Anbar cavabı')], default='text', max_length=32, verbose_name='Növ')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('sent', 'Serverə çatdı'), ('delivered', 'Çatdı'), ('read', 'Oxundu'), ('played', 'Oxundu (səs)'), ('failed', 'Göndərilmədi')], default='pending', max_length=16, verbose_name='Status')),
                ('last_ack', models.SmallIntegerField(blank=True, null=True, verbose_name='WhatsApp ack')),
                ('wa_message_id', models.CharField(blank=True, max_length=128, verbose_name='WhatsApp mesaj ID')),
                ('order_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Sifariş')),
                ('error', models.TextField(blank=True, verbose_name='Xəta')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Göndərildi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Çatdı')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradıldı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yeniləndi')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.restaurant', verbose_name='Restoran')),
            ],
            options={
                'verbose_name': 'WhatsApp mesajı',
                'verbose_name_plural': 'WhatsApp mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='whatsappsession',
            constraint=models.UniqueConstraint(fields=('restaurant',), name='unique_restaurant_whatsapp_session'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['restaurant', '-created_at'], name='users_wa_msg_rest_created'),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('wa_message_id', ''), _negated=True), fields=('restaurant', 'wa_message_id'), name='unique_restaurant_wa_message'),
        ),
    ]
