"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in ('true', '1', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-m5t0j_%cj*lz*#8jlrq$5ua4a4u-9zvh7%9@!4r*3acu3n1r8o',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', default=True)

_allowed_hosts = os.environ.get('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = ['*'] if _allowed_hosts.strip() == '*' else [
    host.strip() for host in _allowed_hosts.split(',') if host.strip()
]

_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if _railway_domain and _railway_domain not in ALLOWED_HOSTS and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_domain)

_csrf_origins = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
if _railway_domain:
    _csrf_origins.append(f'https://{_railway_domain}')
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(_csrf_origins))

# Application definition

INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # apps
    'apps.users.apps.UsersConfig',
    'apps.tables.apps.TablesConfig',
    'apps.orders.apps.OrdersConfig',
    'apps.meals.apps.MealsConfig',
    'apps.finance.apps.FinanceConfig',
    'apps.printers.apps.PrintersConfig',
    'apps.payments.apps.PaymentsConfig',
    'apps.frontend.apps.FrontendConfig',

    # 3rd party apps
    'drf_yasg',
    'corsheaders',
    'logentry_admin',
    'simple_history',
    'rangefilter',
    'inventory',

    # Apps
    'apps.inventory_connector',

    'apps.tenants.apps.TenantsConfig',

    'channels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'apps.tenants.middleware.TenantMiddleware',
    'apps.tables.middleware.DisableCSRFMiddleware',


]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'frontend', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ['DATABASE_URL'],
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'restaurant_db'),
            'USER': os.environ.get('DB_USER', 'aykhan'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'your_password'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'az-az'

TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend', 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.users.auth.PINAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

# Swagger settings (optional)
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'PINAuth': {
            'type': 'apiKey',
            'name': 'X-PIN',
            'in': 'header'
        }
    }
}

AUTH_USER_MODEL = 'users.User'
# username is unique per restaurant, not globally; PIN auth scopes by restaurant.
SILENCED_SYSTEM_CHECKS = ['auth.E003']
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CORS_ALLOWED_ORIGINS = [
#     'https://example.com',
#     'https://www.anotherexample.com',
# ]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'X-PIN',
]


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

CACHE_TIME_IN_SECONDS = 150

_log_handlers = {
    'console': {
        'level': 'INFO',
        'class': 'logging.StreamHandler',
    },
}
if DEBUG:
    _log_handlers['file'] = {
        'level': 'INFO',
        'class': 'logging.FileHandler',
        'filename': os.path.join(BASE_DIR, 'error.log'),
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': _log_handlers,
    'loggers': {
        'django': {
            'handlers': list(_log_handlers.keys()),
            'level': 'INFO',
            'propagate': True,
        },
    },
}

PRINTER_URL = os.environ.get(
    "PRINTER_URL",
    "http://localhost:3000/print"
)
PRINTER_SERVICE = os.environ.get(
    "PRINTER_SERVICE",
    None
)

# Print Gateway (restoran PC → cloud WebSocket)
PRINT_GATEWAY_ENABLED = _env_bool('PRINT_GATEWAY_ENABLED', default=False)
PRINT_GATEWAY_MODE = os.environ.get('PRINT_GATEWAY_MODE', 'websocket')
PRINT_GATEWAY_DEFAULT_LOCATION_ID = os.environ.get('PRINT_GATEWAY_DEFAULT_LOCATION_ID', '1')
PRINT_GATEWAY_TIMEOUT = int(os.environ.get('PRINT_GATEWAY_TIMEOUT', '15'))
PRINT_GATEWAY_URL = os.environ.get('PRINT_GATEWAY_URL', 'http://127.0.0.1:3000')
PRINT_GATEWAY_API_KEY = os.environ.get('PRINT_GATEWAY_API_KEY', '')

_redis_url = os.environ.get('REDIS_URL')
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_redis_url]},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

BACKEND_PORT = os.environ.get('BACKEND_PORT', '8000')

JAZZMIN_SETTINGS = {
    "site_title": "KAZZA Admin",
    "site_header": "KAZZA Panel",
    "site_brand": "KAZZA",
    "welcome_sign": "Xoş gəldiniz!",
    "copyright": "KAZZA Team © 2025",
    "order_with_respect_to": ["tenants", "users", "tables", "meals", "orders", "payments", "finance", "printers"],
}

X_FRAME_OPTIONS = 'ALLOWALL'  # Change value for your need.

# # Base URL for the application (used by Telegram bot)
# BASE_URL = os.environ.get('BASE_URL', 'http://127.0.0.1:8005')

# # Get this from @BotFather
# TELEGRAM_BOT_TOKEN = os.environ.get(
#     'TELEGRAM_BOT_TOKEN', '8559767780:AAHzTCnJPU-h7PGUxwtBi5S3mjgxUpYSZdE')

# WhatsApp Configuration (using WhatsApp Web service)
# URL of the WhatsApp Web service (Node.js service)
WHATSAPP_SERVICE_URL = os.environ.get('WHATSAPP_SERVICE_URL', 'http://localhost:3000')
# Restaurant owner's phone number (format: 501234567 or 994501234567)
RESTAURANT_OWNER_PHONE = os.environ.get('RESTAURANT_OWNER_PHONE', '994518000080')

