# Generated by Django 5.2 on 2025-04-13 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0009_alter_inventoryrecord_reason"),
        ("meals", "0009_meal_preparation_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealInventoryConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_connector",
                        to="meals.meal",
                        verbose_name="Yemək",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yemək üçün anbar əlaqəsi",
                "verbose_name_plural": "Yeməklərin anbar əlaqələri",
            },
        ),
        migrations.CreateModel(
            name="MealInventoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Bu yeməyin 1 vahidi üçün istifadə olunan anbar məhsulunun miqdarı (məs: 0.200 kq)",
                        max_digits=10,
                        verbose_name="Miqdar",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="inventory_connector.mealinventoryconnector",
                        verbose_name="Anbar Əlaqəsi",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_mappings",
                        to="inventory.inventoryitem",
                        verbose_name="Anbar Məhsulu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yemək-Anbar Miqdarı Əlaqəsi",
                "verbose_name_plural": "Yemək-Anbar Miqdarı Əlaqələri",
                "unique_together": {("connector", "inventory_item")},
            },
        ),
        migrations.AddField(
            model_name="mealinventoryconnector",
            name="inventory_items",
            field=models.ManyToManyField(
                through="inventory_connector.MealInventoryMapping",
                to="inventory.inventoryitem",
                verbose_name="Anbar Məhsulları",
            ),
        ),
    ]
