# Generated by Django 5.2 on 2025-04-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_connector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealinventorymapping",
            name="price",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Bu yeməyin 1 vahidi üçün istifadə olunan anbar məhsulunun satış qiyməti (məs: 1.2 AZN)",
                max_digits=10,
                verbose_name="Satış Qiyməti",
            ),
            preserve_default=False,
        ),
    ]
