# Generated by Django 5.2 on 2025-08-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_connector", "0002_mealinventorymapping_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealinventorymapping",
            name="price",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Bu miqdar məhsulun qiyməti. Məsələn: 0.250 kq un üçün 0.75 AZN",
                max_digits=10,
                verbose_name="Satış Qiyməti",
            ),
        ),
        migrations.AlterField(
            model_name="mealinventorymapping",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Bir yeməyin hazırlanması üçün lazım olan məhsul miqdarı. Məsələn: pizza üçün 0.250 kq un",
                max_digits=10,
                verbose_name="Miqdar",
            ),
        ),
    ]
