# Generated by Django 5.2 on 2025-08-30 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_connector", "0003_update_help_texts"),
        ("meals", "0011_alter_meal_updated_at_alter_mealcategory_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mealinventoryconnector",
            options={
                "verbose_name": "Menu üçün anbar əlaqəsi",
                "verbose_name_plural": "Menuların anbar əlaqələri",
            },
        ),
        migrations.AlterModelOptions(
            name="mealinventorymapping",
            options={
                "verbose_name": "Menu-Anbar Miqdarı Əlaqəsi",
                "verbose_name_plural": "Menu-Anbar Miqdarı Əlaqələri",
            },
        ),
        migrations.AlterField(
            model_name="mealinventoryconnector",
            name="meal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_connector",
                to="meals.meal",
                verbose_name="Menu",
            ),
        ),
    ]
