# Generated by Django 5.2 on 2025-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_connector", "0004_update_verbose_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealinventorymapping",
            name="price",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Bu miqdar məhsulun qiyməti. Məsələn: 0.250 kq un üçün 0.75 AZN, 0.200 kq ət üçün 2.50 AZN. Yəni həmin miqdarın dəqiq qiymətini yazın",
                max_digits=10,
                verbose_name="Qiymət (AZN)",
            ),
        ),
        migrations.AlterField(
            model_name="mealinventorymapping",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Bir yeməyin hazırlanması üçün lazım olan məhsul miqdarı. Anbar məhsulunun ölçü vahidi nədirsə, həmin vahiddə daxil edin. Məsələn: pizza üçün 0.250 kq un (250 qram = 0.250 kq), kebab üçün 0.200 kq ət (200 qram = 0.200 kq)",
                max_digits=10,
                verbose_name="Miqdar",
            ),
        ),
    ]
