# Generated by Django 5.2 on 2025-08-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_connector", "0005_update_detailed_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealinventorymapping",
            name="price",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Anbar məhsulunun 1 vahidinin satış qiyməti. Ölçü vahidi kq-sa 1 kq qiyməti, litr-sə 1 litr qiyməti yazın. Məsələn: 1 kq un 3 AZN-dırsa 3 yazın.",
                max_digits=10,
                verbose_name="Vahid Qiymət (AZN)",
            ),
        ),
    ]
