# Generated by Django 4.2.15 on 2025-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Printer Name")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("port", models.IntegerField(default=9100, verbose_name="Port")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the printer",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this is the main printer",
                        verbose_name="Is Main",
                    ),
                ),
            ],
            options={
                "verbose_name": "Printer",
                "verbose_name_plural": "Printers",
            },
        ),
    ]
