# Generated by Django 5.2 on 2025-04-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0031_historicalorderitem_confirmed_orderitem_confirmed"),
        ("payments", "0001_initial"),
        ("printers", "0002_preparationplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Çap tarixi"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("customer", "Müştəri üçün"),
                            ("preperation_places", "Hazırlanma yeri üçün"),
                        ],
                        max_length=20,
                        verbose_name="Çek növü",
                    ),
                ),
                ("text", models.TextField(verbose_name="Çek mətnləri")),
                (
                    "printer_response_status_code",
                    models.IntegerField(
                        default=200, verbose_name="Printer cavab status kodu"
                    ),
                ),
                (
                    "orders",
                    models.ManyToManyField(
                        blank=True, related_name="receipts", to="orders.order"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.payment",
                        verbose_name="Əlaqəli ödəniş",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çek",
                "verbose_name_plural": "Çeklər",
            },
        ),
    ]
