# Generated by Django 5.2 on 2025-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printers", "0005_alter_receipt_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="type",
            field=models.CharField(
                choices=[
                    ("customer", "Müştəri üçün"),
                    ("preperation_places", "Hazırlanma yeri üçün"),
                    ("shift_summary", "Növbə yekunu"),
                    ("z_summary", "Z Hesabat"),
                    ("order_summary", "Sifariş yekunu"),
                ],
                max_length=20,
                verbose_name="Çek növü",
            ),
        ),
    ]
