# Generated by Django 4.2.28 on 2026-06-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_alter_receipt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintGatewayLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location name')),
                ('token', models.CharField(editable=False, help_text='Configure this token in the Print Gateway setup panel.', max_length=64, unique=True, verbose_name='Gateway token')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last seen')),
                ('printers_status', models.JSONField(blank=True, default=dict, verbose_name='Printers status')),
            ],
            options={
                'verbose_name': 'Print gateway location',
                'verbose_name_plural': 'Print gateway locations',
            },
        ),
    ]
